export const rules = [
  {
    id: 'R-042',
    name: 'Severe Malaria — Neurological Signs',
    conditions: [
      { field: 'temperature', operator: '>', value: 38.5 },
      { field: 'consciousnessLevel', operator: '==', value: 'altered' },
      { field: 'respiratoryRate', operator: '>', value: 30 },
    ],
    conclusion: { classification: 'SEVERE_MALARIA', action: 'URGENT_REFERRAL' },
    confidence: 98,
    treatment: 'Administer IV Artesunate immediately. Refer patient urgently to nearest hospital. Monitor breathing and consciousness continuously during transfer.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 7.3',
    explanation: 'Severe malaria was indicated by high fever (above 38.5°C), altered consciousness, and rapid breathing (above 30 breaths per minute).',
  },
  {
    id: 'R-043',
    name: 'Severe Malaria — Unconscious Patient',
    conditions: [
      { field: 'temperature', operator: '>', value: 38.5 },
      { field: 'consciousnessLevel', operator: '==', value: 'unconscious' },
    ],
    conclusion: { classification: 'SEVERE_MALARIA', action: 'URGENT_REFERRAL' },
    confidence: 99,
    treatment: 'Administer IV Artesunate immediately. Refer patient urgently to nearest hospital. This is a medical emergency.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 7.3',
    explanation: 'Severe malaria was indicated because the patient is unconscious with high fever — a sign of cerebral malaria.',
  },
  {
    id: 'R-044',
    name: 'Severe Malaria — Confusion with Fever',
    conditions: [
      { field: 'temperature', operator: '>', value: 38.5 },
      { field: 'consciousnessLevel', operator: '==', value: 'confused' },
      { field: 'rdtResult', operator: '==', value: 'positive' },
    ],
    conclusion: { classification: 'SEVERE_MALARIA', action: 'URGENT_REFERRAL' },
    confidence: 95,
    treatment: 'Administer IV Artesunate immediately. Refer patient urgently to nearest hospital.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 7.3',
    explanation: 'Severe malaria was indicated by high fever, confusion, and a positive RDT result.',
  },
  {
    id: 'R-001',
    name: 'Uncomplicated Malaria — Positive RDT, No Danger Signs',
    conditions: [
      { field: 'fever', operator: '==', value: true },
      { field: 'rdtResult', operator: '==', value: 'positive' },
      { field: 'consciousnessLevel', operator: '==', value: 'alert' },
    ],
    conclusion: { classification: 'UNCOMPLICATED_MALARIA', action: 'TREAT' },
    confidence: 95,
    treatment: 'Administer oral Artemisinin-based Combination Therapy (ACT) for 3 days. Ensure patient completes the full course. Review in 48 hours if no improvement.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 6.1',
    explanation: 'Uncomplicated malaria was indicated by fever and a positive RDT result with no danger signs present.',
  },
  {
    id: 'R-002',
    name: 'Uncomplicated Malaria — High Risk Patient',
    conditions: [
      { field: 'fever', operator: '==', value: true },
      { field: 'locationZone', operator: '==', value: 'high' },
      { field: 'rdtResult', operator: '==', value: 'positive' },
    ],
    conclusion: { classification: 'UNCOMPLICATED_MALARIA', action: 'TREAT' },
    confidence: 92,
    treatment: 'Administer oral ACT for 3 days. High transmission zone — monitor closely. Review in 24 hours.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 6.1',
    explanation: 'Uncomplicated malaria was indicated by fever, positive RDT, and location in a high transmission zone.',
  },
  {
    id: 'R-017',
    name: 'Non-Malarial Fever — Negative RDT, Short Duration',
    conditions: [
      { field: 'fever', operator: '==', value: true },
      { field: 'rdtResult', operator: '==', value: 'negative' },
      { field: 'durationDays', operator: '<', value: 3 },
    ],
    conclusion: { classification: 'NON_MALARIAL_FEVER', action: 'FURTHER_INVESTIGATION' },
    confidence: 80,
    treatment: 'Malaria is unlikely. Investigate other causes of fever such as respiratory infection, typhoid, or urinary tract infection. Do not administer antimalarials.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 4.2',
    explanation: 'Non-malarial fever was indicated by a negative RDT result and short symptom duration of less than 3 days.',
  },
  {
    id: 'R-018',
    name: 'Non-Malarial Fever — Negative RDT, Low Transmission Zone',
    conditions: [
      { field: 'fever', operator: '==', value: true },
      { field: 'rdtResult', operator: '==', value: 'negative' },
      { field: 'locationZone', operator: '==', value: 'low' },
    ],
    conclusion: { classification: 'NON_MALARIAL_FEVER', action: 'FURTHER_INVESTIGATION' },
    confidence: 78,
    treatment: 'Malaria is unlikely given the negative RDT and low transmission zone. Investigate other causes. Do not administer antimalarials without further confirmation.',
    source: 'WHO Malaria Treatment Guidelines 2022, Section 4.2',
    explanation: 'Non-malarial fever was indicated by a negative RDT result in a low malaria transmission zone.',
  },
];